BLOCKS_SCHEMA = [
    {
        "name": "number",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "The block number",
    },
    {
        "name": "hash",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Hash of the block",
    },
    {
        "name": "parent_hash",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Hash of the parent block",
    },
    {
        "name": "logs_bloom",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The bloom filter for the logs of the block",
    },
    {
        "name": "transactions_root",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The root of the transaction trie of the block",
    },
    {
        "name": "state_root",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The root of the final state trie of the block",
    },
    {
        "name": "receipts_root",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The root of the receipts trie of the block",
    },
    {
        "name": "size",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "The size of this block in bytes",
    },
    {
        "name": "extra_data",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The extra data field of this block",
    },
    {
        "name": "gas_used",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "The total used gas by all transactions in this block",
    },
    {
        "name": "block_timestamp",
        "type": "TIMESTAMP",
        "mode": "NULLABLE",
        "description": "The UTC timestamp for when the block was collated",
    },
    {
        "name": "block_unix_timestamp",
        "type": "FLOAT64",
        "mode": "NULLABLE",
        "description": "The unix timestamp for when the block was collated",
    },
    {
        "name": "transaction_count",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "The number of transactions in the block",
    },
    {
        "name": "block_score",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "Former difficulty. Always 1 in the BFT consensus engine",
    },
    {
        "name": "total_block_score",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "Integer of the total blockScore of the chain until this block",
    },
    {
        "name": "governance_data",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "RLP encoded governance configuration",
    },
    {
        "name": "vote_data",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "RLP encoded governance vote of the proposer",
    },
    {
        "name": "committee",
        "type": "STRING",
        "mode": "REPEATED",
        "description": "Array of addresses of committee members of this block. The committee is a subset of validators participated in the consensus protocol for this block",
    },
    {
        "name": "proposer",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The address of the block proposer",
    },
    {
        "name": "reward_address",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The address of the beneficiary to whom the block rewards were givem",
    },
    {
        "name": "base_fee_per_gas",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "The base fee per gas. This value is returned only when EthTxTypeCompatibleBlock is activated for that block number",
    },
]
