RECEIPTS_SCHEMA = [
    {
        "name": "transaction_hash",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Hash of the transactions",
    },
    {
        "name": "transaction_index",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "Integer of the transactions index position in the block",
    },
    {
        "name": "block_hash",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Hash of the block",
    },
    {
        "name": "block_number",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "Block number corresponding",
    },
    {
        "name": "gas",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "Gas provided by the sender",
    },
    {
        "name": "gas_price",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "Gas price provided by the sender in Peb",
    },
    {
        "name": "gas_used",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "The total used gas by all transactions in this block",
    },
    {
        "name": "effective_gas_price",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "The actual value per gas deducted from the senders account",
    },
    {
        "name": "contract_address",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The contract address created, if the transaction was a contract creation, otherwise null",
    },
    {
        "name": "logs_bloom",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The bloom filter for the logs",
    },
    {
        "name": "nonce",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "The number of transactions made by the sender prior to this one",
    },
    {
        "name": "fee_payer",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "(optional) Address of the fee payer",
    },
    {
        "name": "fee_payer_signatures",
        "type": "STRUCT",
        "mode": "REPEATED",
        "fields": [
            {"name": "V", "type": "STRING"},
            {"name": "R", "type": "STRING"},
            {"name": "S", "type": "STRING"},
        ],
        "description": "(optional) An array of fee payer’s signature objects. A signature object contains three fields (V, R, and S). V contains ECDSA recovery id. R contains ECDSA signature r while S contains ECDSA signature s",
    },
    {
        "name": "fee_ratio",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "(optional) Fee ratio of the fee payer. If it is 30, 30% of the fee will be paid by the fee payer. 70% will be paid by the sender",
    },
    {
        "name": "code_format",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "(optional) The code format of smart contract code",
    },
    {
        "name": "human_readable",
        "type": "BOOL",
        "mode": "NULLABLE",
        "description": "(optional) true if the address is humanReadable, false if the address is not humanReadable",
    },
    {
        "name": "tx_error",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "(optional) detailed error code if status is equal to zero",
    },
    {
        "name": "key",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "(optional) key of the newly created account",
    },
    {
        "name": "input_data",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "(optional) The data sent along with the transaction",
    },
    {
        "name": "from_address",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Address of the sender",
    },
    {
        "name": "to_address",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Address of the receiver. Null when it is a contract creation transaction",
    },
    {
        "name": "type_name",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "A string representing the type of the transaction",
    },
    {
        "name": "type_int",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "An integer representing the type of the transaction",
    },
    {
        "name": "sender_tx_hash",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Hash of a transaction that is signed only by the sender",
    },
    {
        "name": "signatures",
        "type": "STRUCT",
        "mode": "REPEATED",
        "fields": [
            {"name": "V", "type": "STRING"},
            {"name": "R", "type": "STRING"},
            {"name": "S", "type": "STRING"},
        ],
        "description": "An array of signature objects. A signature object contains three fields (V, R, and S). V contains ECDSA recovery id. R contains ECDSA signature r while S contains ECDSA signature s",
    },
    {
        "name": "status",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "Either 1 (success) or 0 (failure)",
    },
    {
        "name": "value",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "(optional) Integer of the value sent with this transaction",
    },
    {
        "name": "input_json",
        "type": "STRUCT",
        "mode": "NULLABLE",
        "fields": [
            {"name": "blockCount", "type": "INT64"},
            {"name": "blockHash", "type": "STRING"},
            {"name": "blockNumber", "type": "INT64"},
            {"name": "id", "type": "STRING"},
            {"name": "parentHash", "type": "STRING"},
            {"name": "receiptsRoot", "type": "STRING"},
            {"name": "stateRoot", "type": "STRING"},
            {"name": "transactionsRoot", "type": "STRING"},
            {"name": "txCount", "type": "INT64"},
        ],
        "description": "(optional) The data sent along with the transaction",
    },
    {
        "name": "access_list",
        "type": "STRUCT",
        "mode": "REPEATED",
        "fields": [
            {"name": "address", "type": "STRING"},
            {"name": "storage_keys", "type": "STRING", "mode": "REPEATED"},
        ],
        "description": "An array of accessList",
    },
    {
        "name": "chain_id",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "id of the chain",
    },
    {
        "name": "max_priority_fee_per_gas",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "A maximum amount to pay for the transaction to execute",
    },
    {
        "name": "max_fee_per_gas",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "Gas tip cap for dynamic fee transaction in peb",
    },
    {
        "name": "block_timestamp",
        "type": "TIMESTAMP",
        "mode": "NULLABLE",
        "description": "The UTC timestamp for when the block was collated",
    },
    {
        "name": "block_unix_timestamp",
        "type": "FLOAT64",
        "mode": "NULLABLE",
        "description": "The unix timestamp for when the block was collated",
    },
]
