TRACES_SCHEMA = [
    {
        "name": "block_number",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "Block number corresponding",
    },
    {
        "name": "block_hash",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Hash of the block",
    },
    {
        "name": "block_timestamp",
        "type": "TIMESTAMP",
        "mode": "NULLABLE",
        "description": "The UTC timestamp for when the block was collated",
    },
    {
        "name": "block_unix_timestamp",
        "type": "FLOAT64",
        "mode": "NULLABLE",
        "description": "The unix timestamp for when the block was collated",
    },
    {
        "name": "transaction_hash",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Integer of the transactions index position in the block",
    },
    {
        "name": "transaction_index",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "Hash of the transactions",
    },
    {
        "name": "transaction_receipt_status",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "Either 1 (success) or 0 (failure) (post Byzantium)",
    },
    {
        "name": "from_address",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Address of the sender, null when trace_type is reward",
    },
    {
        "name": "to_address",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Address of the receiver if trace_type is call, address of new contract or null if trace_type is create (or create 2), beneficiary address if trace_type is suicide, miner address if trace_type is reward",
    },
    {
        "name": "value",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "Value transferred in Peb",
    },
    {
        "name": "input",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The data sent along with the message call",
    },
    {
        "name": "output",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "The output of the message call, bytecode of contract when trace_type is create",
    },
    {
        "name": "trace_type",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "One of call, create, create2, suicide, reward",
    },
    {
        "name": "call_type",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "One of call, callcode, delegatecall, staticcall",
    },
    {
        "name": "gas",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "Gas provided with the message call",
    },
    {
        "name": "gas_used",
        "type": "DECIMAL",
        "mode": "NULLABLE",
        "description": "Gas used by the message call",
    },
    {
        "name": "subtraces",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "Number of subtraces",
    },
    {
        "name": "trace_address",
        "type": "STRING",
        "mode": "REPEATED",
        "description": "Comma separated list of trace address in call tree",
    },
    {
        "name": "error",
        "type": "STRING",
        "mode": "NULLABLE",
        "description": "Error message",
    },
    {
        "name": "status",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "Either 1 (success) or 0 (failure, due to any operation that can cause the call itself or any top-level call to revert)",
    },
    {
        "name": "trace_index",
        "type": "INT64",
        "mode": "NULLABLE",
        "description": "Trace index of the trace",
    },
]
