name: Publish pypi package
on:
  push:
    tags:
     - v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Build python package
      run: |
        echo ${{ github.ref_name }} > VERSION
        python -m pip install build wheel twine
        python setup.py bdist_wheel
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}

